/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_SDGPlantation (void)
{
  GtkWidget *SDGPlantation;
  GtkWidget *fixed1;
  GtkWidget *calendar1;
  GtkWidget *buttonSD1;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label1;
  GtkWidget *labelSD1;
  GtkWidget *notebookSD;
  GtkWidget *fixed2;
  GtkWidget *treeviewerSD;
  GtkWidget *buttonSD2;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label6;
  GtkWidget *buttonSD4;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label8;
  GtkWidget *buttonSD3;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label7;
  GtkWidget *labelSD2;
  GtkWidget *fixed3;
  GtkWidget *entrySD5;
  GtkWidget *entrySD6;
  GtkWidget *entrySD7;
  GtkWidget *entrySD8;
  GtkWidget *entrySD9;
  GtkWidget *entry6SD10;
  GtkWidget *entrySD11;
  GtkWidget *labelSD11;
  GtkWidget *labelSD10;
  GtkWidget *labelSD9;
  GtkWidget *labelSD8;
  GtkWidget *labelSD7;
  GtkWidget *labelSD6;
  GtkWidget *labelSD5;
  GtkWidget *buttonSD5;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label16;
  GtkWidget *buttonSD6;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label17;
  GtkWidget *buttonSD7;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label18;
  GtkWidget *imageSD;
  GtkWidget *labelSD3;
  GtkWidget *fixed4;
  GtkWidget *entrySD12;
  GtkWidget *labelSD12;
  GtkWidget *textviewSD;
  GtkWidget *buttonSD9;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image9;
  GtkWidget *label20;
  GtkWidget *imageSD2;
  GtkWidget *labelSD4;

  SDGPlantation = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (SDGPlantation), _("Gestion des plantations vegetales"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (SDGPlantation), fixed1);

  calendar1 = gtk_calendar_new ();
  gtk_widget_show (calendar1);
  gtk_fixed_put (GTK_FIXED (fixed1), calendar1, 8, 8);
  gtk_widget_set_size_request (calendar1, 120, 120);
  gtk_calendar_display_options (GTK_CALENDAR (calendar1),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  buttonSD1 = gtk_button_new ();
  gtk_widget_show (buttonSD1);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonSD1, 528, 8);
  gtk_widget_set_size_request (buttonSD1, 88, 29);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (buttonSD1), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label1 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (hbox1), label1, FALSE, FALSE, 0);

  labelSD1 = gtk_label_new (_("Gestion des plantations vegetales"));
  gtk_widget_show (labelSD1);
  gtk_fixed_put (GTK_FIXED (fixed1), labelSD1, 200, 8);
  gtk_widget_set_size_request (labelSD1, 280, 24);
  gtk_label_set_justify (GTK_LABEL (labelSD1), GTK_JUSTIFY_CENTER);

  notebookSD = gtk_notebook_new ();
  gtk_widget_show (notebookSD);
  gtk_fixed_put (GTK_FIXED (fixed1), notebookSD, 144, 56);
  gtk_widget_set_size_request (notebookSD, 544, 376);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (notebookSD), fixed2);

  treeviewerSD = gtk_tree_view_new ();
  gtk_widget_show (treeviewerSD);
  gtk_fixed_put (GTK_FIXED (fixed2), treeviewerSD, 16, 24);
  gtk_widget_set_size_request (treeviewerSD, 296, 192);

  buttonSD2 = gtk_button_new ();
  gtk_widget_show (buttonSD2);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonSD2, 360, 72);
  gtk_widget_set_size_request (buttonSD2, 104, 32);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (buttonSD2), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label6 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox2), label6, FALSE, FALSE, 0);

  buttonSD4 = gtk_button_new ();
  gtk_widget_show (buttonSD4);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonSD4, 360, 152);
  gtk_widget_set_size_request (buttonSD4, 104, 32);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (buttonSD4), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label8 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (hbox4), label8, FALSE, FALSE, 0);

  buttonSD3 = gtk_button_new ();
  gtk_widget_show (buttonSD3);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonSD3, 360, 112);
  gtk_widget_set_size_request (buttonSD3, 104, 32);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (buttonSD3), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label7 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox3), label7, FALSE, FALSE, 0);

  labelSD2 = gtk_label_new (_("Liste varietes"));
  gtk_widget_show (labelSD2);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebookSD), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebookSD), 0), labelSD2);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (notebookSD), fixed3);

  entrySD5 = gtk_entry_new ();
  gtk_widget_show (entrySD5);
  gtk_fixed_put (GTK_FIXED (fixed3), entrySD5, 112, 8);
  gtk_widget_set_size_request (entrySD5, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrySD5), 8226);

  entrySD6 = gtk_entry_new ();
  gtk_widget_show (entrySD6);
  gtk_fixed_put (GTK_FIXED (fixed3), entrySD6, 80, 48);
  gtk_widget_set_size_request (entrySD6, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrySD6), 8226);

  entrySD7 = gtk_entry_new ();
  gtk_widget_show (entrySD7);
  gtk_fixed_put (GTK_FIXED (fixed3), entrySD7, 104, 88);
  gtk_widget_set_size_request (entrySD7, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrySD7), 8226);

  entrySD8 = gtk_entry_new ();
  gtk_widget_show (entrySD8);
  gtk_fixed_put (GTK_FIXED (fixed3), entrySD8, 152, 128);
  gtk_widget_set_size_request (entrySD8, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrySD8), 8226);

  entrySD9 = gtk_entry_new ();
  gtk_widget_show (entrySD9);
  gtk_fixed_put (GTK_FIXED (fixed3), entrySD9, 160, 168);
  gtk_widget_set_size_request (entrySD9, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrySD9), 8226);

  entry6SD10 = gtk_entry_new ();
  gtk_widget_show (entry6SD10);
  gtk_fixed_put (GTK_FIXED (fixed3), entry6SD10, 160, 208);
  gtk_widget_set_size_request (entry6SD10, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry6SD10), 8226);

  entrySD11 = gtk_entry_new ();
  gtk_widget_show (entrySD11);
  gtk_fixed_put (GTK_FIXED (fixed3), entrySD11, 160, 248);
  gtk_widget_set_size_request (entrySD11, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrySD11), 8226);

  labelSD11 = gtk_label_new (_("Production annuelle"));
  gtk_widget_show (labelSD11);
  gtk_fixed_put (GTK_FIXED (fixed3), labelSD11, 16, 256);
  gtk_widget_set_size_request (labelSD11, 144, 16);

  labelSD10 = gtk_label_new (_("Periode mise engrais"));
  gtk_widget_show (labelSD10);
  gtk_fixed_put (GTK_FIXED (fixed3), labelSD10, 8, 216);
  gtk_widget_set_size_request (labelSD10, 160, 16);

  labelSD9 = gtk_label_new (_("Periode d'irrigation"));
  gtk_widget_show (labelSD9);
  gtk_fixed_put (GTK_FIXED (fixed3), labelSD9, 8, 176);
  gtk_widget_set_size_request (labelSD9, 152, 17);

  labelSD8 = gtk_label_new (_("Periode plantation"));
  gtk_widget_show (labelSD8);
  gtk_fixed_put (GTK_FIXED (fixed3), labelSD8, 8, 136);
  gtk_widget_set_size_request (labelSD8, 144, 16);

  labelSD7 = gtk_label_new (_("Espacement"));
  gtk_widget_show (labelSD7);
  gtk_fixed_put (GTK_FIXED (fixed3), labelSD7, 8, 96);
  gtk_widget_set_size_request (labelSD7, 96, 17);

  labelSD6 = gtk_label_new (_("Quantite"));
  gtk_widget_show (labelSD6);
  gtk_fixed_put (GTK_FIXED (fixed3), labelSD6, 8, 56);
  gtk_widget_set_size_request (labelSD6, 80, 16);

  labelSD5 = gtk_label_new (_("Nom variete"));
  gtk_widget_show (labelSD5);
  gtk_fixed_put (GTK_FIXED (fixed3), labelSD5, 0, 16);
  gtk_widget_set_size_request (labelSD5, 120, 16);

  buttonSD5 = gtk_button_new ();
  gtk_widget_show (buttonSD5);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonSD5, 416, 184);
  gtk_widget_set_size_request (buttonSD5, 104, 32);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (buttonSD5), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label16 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label16);
  gtk_box_pack_start (GTK_BOX (hbox5), label16, FALSE, FALSE, 0);

  buttonSD6 = gtk_button_new ();
  gtk_widget_show (buttonSD6);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonSD6, 416, 224);
  gtk_widget_set_size_request (buttonSD6, 104, 32);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (buttonSD6), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label17 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label17);
  gtk_box_pack_start (GTK_BOX (hbox6), label17, FALSE, FALSE, 0);

  buttonSD7 = gtk_button_new ();
  gtk_widget_show (buttonSD7);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonSD7, 416, 264);
  gtk_widget_set_size_request (buttonSD7, 104, 32);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (buttonSD7), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label18 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label18);
  gtk_box_pack_start (GTK_BOX (hbox7), label18, FALSE, FALSE, 0);

  imageSD = create_pixmap (SDGPlantation, "5.jpeg");
  gtk_widget_show (imageSD);
  gtk_fixed_put (GTK_FIXED (fixed3), imageSD, 336, 8);
  gtk_widget_set_size_request (imageSD, 192, 152);

  labelSD3 = gtk_label_new (_("Ajout variete"));
  gtk_widget_show (labelSD3);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebookSD), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebookSD), 1), labelSD3);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (notebookSD), fixed4);

  entrySD12 = gtk_entry_new ();
  gtk_widget_show (entrySD12);
  gtk_fixed_put (GTK_FIXED (fixed4), entrySD12, 192, 32);
  gtk_widget_set_size_request (entrySD12, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrySD12), 8226);

  labelSD12 = gtk_label_new (_("Taper un mot a chercher"));
  gtk_widget_show (labelSD12);
  gtk_fixed_put (GTK_FIXED (fixed4), labelSD12, 0, 40);
  gtk_widget_set_size_request (labelSD12, 200, 24);

  textviewSD = gtk_text_view_new ();
  gtk_widget_show (textviewSD);
  gtk_fixed_put (GTK_FIXED (fixed4), textviewSD, 144, 112);
  gtk_widget_set_size_request (textviewSD, 360, 144);

  buttonSD9 = gtk_button_new ();
  gtk_widget_show (buttonSD9);
  gtk_fixed_put (GTK_FIXED (fixed4), buttonSD9, 368, 32);
  gtk_widget_set_size_request (buttonSD9, 112, 32);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (buttonSD9), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image9 = gtk_image_new_from_stock ("gtk-dialog-question", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox8), image9, FALSE, FALSE, 0);

  label20 = gtk_label_new_with_mnemonic (_("Recherche"));
  gtk_widget_show (label20);
  gtk_box_pack_start (GTK_BOX (hbox8), label20, FALSE, FALSE, 0);

  imageSD2 = create_pixmap (SDGPlantation, "6.jpeg");
  gtk_widget_show (imageSD2);
  gtk_fixed_put (GTK_FIXED (fixed4), imageSD2, 0, 80);
  gtk_widget_set_size_request (imageSD2, 144, 208);

  labelSD4 = gtk_label_new (_("Recherche"));
  gtk_widget_show (labelSD4);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebookSD), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebookSD), 2), labelSD4);

  g_signal_connect ((gpointer) buttonSD2, "clicked",
                    G_CALLBACK (on_buttonSD2_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonSD4, "clicked",
                    G_CALLBACK (on_buttonSD4_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonSD3, "clicked",
                    G_CALLBACK (on_buttonSD3_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonSD5, "clicked",
                    G_CALLBACK (on_buttonSD5_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonSD6, "clicked",
                    G_CALLBACK (on_buttonSD6_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonSD7, "clicked",
                    G_CALLBACK (on_buttonSD7_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonSD9, "clicked",
                    G_CALLBACK (on_buttonSD9_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (SDGPlantation, SDGPlantation, "SDGPlantation");
  GLADE_HOOKUP_OBJECT (SDGPlantation, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (SDGPlantation, calendar1, "calendar1");
  GLADE_HOOKUP_OBJECT (SDGPlantation, buttonSD1, "buttonSD1");
  GLADE_HOOKUP_OBJECT (SDGPlantation, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (SDGPlantation, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (SDGPlantation, image1, "image1");
  GLADE_HOOKUP_OBJECT (SDGPlantation, label1, "label1");
  GLADE_HOOKUP_OBJECT (SDGPlantation, labelSD1, "labelSD1");
  GLADE_HOOKUP_OBJECT (SDGPlantation, notebookSD, "notebookSD");
  GLADE_HOOKUP_OBJECT (SDGPlantation, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (SDGPlantation, treeviewerSD, "treeviewerSD");
  GLADE_HOOKUP_OBJECT (SDGPlantation, buttonSD2, "buttonSD2");
  GLADE_HOOKUP_OBJECT (SDGPlantation, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (SDGPlantation, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (SDGPlantation, image2, "image2");
  GLADE_HOOKUP_OBJECT (SDGPlantation, label6, "label6");
  GLADE_HOOKUP_OBJECT (SDGPlantation, buttonSD4, "buttonSD4");
  GLADE_HOOKUP_OBJECT (SDGPlantation, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (SDGPlantation, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (SDGPlantation, image4, "image4");
  GLADE_HOOKUP_OBJECT (SDGPlantation, label8, "label8");
  GLADE_HOOKUP_OBJECT (SDGPlantation, buttonSD3, "buttonSD3");
  GLADE_HOOKUP_OBJECT (SDGPlantation, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (SDGPlantation, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (SDGPlantation, image3, "image3");
  GLADE_HOOKUP_OBJECT (SDGPlantation, label7, "label7");
  GLADE_HOOKUP_OBJECT (SDGPlantation, labelSD2, "labelSD2");
  GLADE_HOOKUP_OBJECT (SDGPlantation, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (SDGPlantation, entrySD5, "entrySD5");
  GLADE_HOOKUP_OBJECT (SDGPlantation, entrySD6, "entrySD6");
  GLADE_HOOKUP_OBJECT (SDGPlantation, entrySD7, "entrySD7");
  GLADE_HOOKUP_OBJECT (SDGPlantation, entrySD8, "entrySD8");
  GLADE_HOOKUP_OBJECT (SDGPlantation, entrySD9, "entrySD9");
  GLADE_HOOKUP_OBJECT (SDGPlantation, entry6SD10, "entry6SD10");
  GLADE_HOOKUP_OBJECT (SDGPlantation, entrySD11, "entrySD11");
  GLADE_HOOKUP_OBJECT (SDGPlantation, labelSD11, "labelSD11");
  GLADE_HOOKUP_OBJECT (SDGPlantation, labelSD10, "labelSD10");
  GLADE_HOOKUP_OBJECT (SDGPlantation, labelSD9, "labelSD9");
  GLADE_HOOKUP_OBJECT (SDGPlantation, labelSD8, "labelSD8");
  GLADE_HOOKUP_OBJECT (SDGPlantation, labelSD7, "labelSD7");
  GLADE_HOOKUP_OBJECT (SDGPlantation, labelSD6, "labelSD6");
  GLADE_HOOKUP_OBJECT (SDGPlantation, labelSD5, "labelSD5");
  GLADE_HOOKUP_OBJECT (SDGPlantation, buttonSD5, "buttonSD5");
  GLADE_HOOKUP_OBJECT (SDGPlantation, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (SDGPlantation, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (SDGPlantation, image5, "image5");
  GLADE_HOOKUP_OBJECT (SDGPlantation, label16, "label16");
  GLADE_HOOKUP_OBJECT (SDGPlantation, buttonSD6, "buttonSD6");
  GLADE_HOOKUP_OBJECT (SDGPlantation, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (SDGPlantation, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (SDGPlantation, image6, "image6");
  GLADE_HOOKUP_OBJECT (SDGPlantation, label17, "label17");
  GLADE_HOOKUP_OBJECT (SDGPlantation, buttonSD7, "buttonSD7");
  GLADE_HOOKUP_OBJECT (SDGPlantation, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (SDGPlantation, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (SDGPlantation, image7, "image7");
  GLADE_HOOKUP_OBJECT (SDGPlantation, label18, "label18");
  GLADE_HOOKUP_OBJECT (SDGPlantation, imageSD, "imageSD");
  GLADE_HOOKUP_OBJECT (SDGPlantation, labelSD3, "labelSD3");
  GLADE_HOOKUP_OBJECT (SDGPlantation, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (SDGPlantation, entrySD12, "entrySD12");
  GLADE_HOOKUP_OBJECT (SDGPlantation, labelSD12, "labelSD12");
  GLADE_HOOKUP_OBJECT (SDGPlantation, textviewSD, "textviewSD");
  GLADE_HOOKUP_OBJECT (SDGPlantation, buttonSD9, "buttonSD9");
  GLADE_HOOKUP_OBJECT (SDGPlantation, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (SDGPlantation, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (SDGPlantation, image9, "image9");
  GLADE_HOOKUP_OBJECT (SDGPlantation, label20, "label20");
  GLADE_HOOKUP_OBJECT (SDGPlantation, imageSD2, "imageSD2");
  GLADE_HOOKUP_OBJECT (SDGPlantation, labelSD4, "labelSD4");

  return SDGPlantation;
}

